export const DEFAULT_PURITY = 0.5
export const DEFAULT_PLOIDY = 2
export const CN_STATES = [[1, 1], [1, 0], [2, 0], [2, 1], [3, 1], [4, 2], [3, 2]]
export const START_CN = 0;
export const END_CN = 20;
export const UNCLUSTERED_ID = "-1";
export const DELETED_ID = "-2";
export const MAX_PLOIDY = 12;
export const MIN_PLOIDY = 1;
export const MAX_PURITY = 1;
export const MIN_PURITY = 0;